language: python
python:
  - "3.6.2"
# command to install dependencies
install: 
 - pip install -r requirements.txt
 - pip install nose
 - pip install python-coveralls
 - pip install coverage
# command to run tests
script: 
 - pytest test/
 - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  - coveralls
branches:
  only:
    - master