version: '3'

# docker-compose maneja una red interna donde mapea cada modulo a una url
services:
  appserv:
    # el modulo product-service se construye a partir del Dockerfile y los archivos de product/
    build: ./
    volumes:
      # product-service esta basado en la image python:3 la cual requiere que los source files se depositen en /usr/src/app
      - ./:/usr/src/app
    ports:
      - 5000:5000
      - 8000:8000
    environment: 
      - DATABASE_URL=appmongo

  appmongo:
    image: mongo:3.4
    ports:
      - 27017:27017
